### ISSUE TITLE
程序功能的扩展问题

### ISSUE THREAD

**Issue by DengCaiYun** [kagana/wifiAnalysis#2]
如何保存墙壁障碍物呢？也就是说如何直接通过读取mat文件中的坐标对得出当前的房间构图呢？
How to get the drawing of room by directly reading the mat file  to avoid clicking repeatly every time I run the program

**Comment by kagana** [comment]
Hello, 
First draw your walls and then save them by the following command:
>> save('wallData.mat','ldata','p');

From now on, you can load your walls without drawing again.
>> load wallData;
>> evalData

**Comment by DengCaiYun** [comment]
Thank you for your replying. I solved this problem under your guidement.But I got another problem:
how can I only show the wall with 'wallData.mat'? the following is my trial,but it does not work well,

first,l I draw wall in getData1.m as follws:
![getdata1](https://cloud.githubusercontent.com/assets/9544333/20128620/701100ac-a684-11e6-8208-54a2b575dc78.png)
then I run the code:
global ldata dm p
load wallData;
nlines = size(ldata,1);
nlines
figure(2)
for i = 1:nlines
    line(ldata(1,1:2), ldata(1,3:4));
end
the result is:
![qq 20161109135715](https://cloud.githubusercontent.com/assets/9544333/20128596/3ab3e370-a684-11e6-9b86-a96cca33c1b8.png)
It only show the first wall I draw in getData1.m,and I didnot find where I did wrong,can you please help me?

**Comment by DengCaiYun** [comment]
I got the solution now, I made a mistake by using line(ldata(1,1:2), ldata(1,3:4)), I should use i other than 1, what a funny mistake!!
